spring:
  thymeleaf:
    cache: false

app:
  edit-path: https://abc.com/todos/edit
  cron-exp: 0 0 0,6 * * ?

line.bot:
  channel-token: 'sgfKNAVMJZOWMLxDwATlwZqP32fKGCxHRQfSF66jEivmAwpv1U4cOSVRgoMM8NX/rHT6sAhr1lmRZaWvoXSrRUjOI5K4KqZjuSaiIupGH56PRRwoy00xeIOIXqoNNnIYhK8MUD5BoFNhsJDZcee6TAdB04t89/1O/w1cDnyilFU='
  channel-secret: '8a45e326416403266afe7fdd9182b51a'
  handle-path: /callback

line.login:
  client_id: '1655981933'
  client_secret: 'e47ac643b3c92f785eafc34d69fc40b5'
  redirect_uri: https://linenotificationtest.herokuapp.com/login/oauth2/code/line
